// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SnapLink_Repository.Entity;

public partial class Administrator
{
    public int AdminId { get; set; }

    public int UserId { get; set; }

    public string AccessLevel { get; set; }

    public string Department { get; set; }

    public virtual User User { get; set; }
}