// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SnapLink_Repository.Entity;

public partial class LocationImage
{
    public int LocationImageId { get; set; }

    public int LocationId { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsPrimary { get; set; }

    public string Caption { get; set; }

    public DateTime? UploadedAt { get; set; }

    public virtual Location Location { get; set; }
}