// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SnapLink_Repository.Entity;

public partial class Messagess
{
    public int MessageId { get; set; }

    public int? SenderId { get; set; }

    public int? RecipientId { get; set; }

    public string Content { get; set; }

    public string AttachmentUrl { get; set; }

    public bool? ReadStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Recipient { get; set; }

    public virtual User Sender { get; set; }
}