// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SnapLink_Repository.Entity;

public partial class PhotographerStyle
{
    public int PhotographerStyleId { get; set; }

    public int PhotographerId { get; set; }

    public int StyleId { get; set; }

    public virtual Photographer Photographer { get; set; }

    public virtual Style Style { get; set; }
}