// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SnapLink_Repository.Entity;

public partial class Photographer
{
    public int PhotographerId { get; set; }

    public int UserId { get; set; }

    public int? YearsExperience { get; set; }

    public string Equipment { get; set; }

    public string Specialty { get; set; }

    public string PortfolioUrl { get; set; }

    public decimal? HourlyRate { get; set; }

    public string AvailabilityStatus { get; set; }

    public decimal? Rating { get; set; }

    public bool? FeaturedStatus { get; set; }

    public string VerificationStatus { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<PhotographerStyle> PhotographerStyles { get; set; } = new List<PhotographerStyle>();

    public virtual ICollection<PhotographerWallet> PhotographerWallets { get; set; } = new List<PhotographerWallet>();

    public virtual User User { get; set; }

    public virtual ICollection<WithdrawalRequest> WithdrawalRequests { get; set; } = new List<WithdrawalRequest>();
}