// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SnapLink_Repository.Entity;

public partial class PremiumSubscription
{
    public int PremiumSubscriptionId { get; set; }

    public int UserId { get; set; }

    public int PackageId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Status { get; set; }

    public int? PaymentId { get; set; }

    public virtual PremiumPackage Package { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual User User { get; set; }
}